data-oss, ebtables do_configure depends on virtual/kernel:do_shared_workdir
This change is to fix following error:

 librmnetctl.c:50:10: fatal error: linux/rmnet_data.h: No such file or directory
  #include <linux/rmnet_data.h>
           ^~~~~~~~~~~~~~~~~~~~
 compilation terminated.

Change-Id: I98893ce338ca51ac3e51e550f902ff6169efc87f