meta-qti-data: add depends on virtual/kernel do_shared_workdir
data:
librmnetctl.c:55:10: fatal error: linux/rmnet_data.h: No such file or directory
   55 | #include <linux/rmnet_data.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
ebtables:
ebt_ulog.h': No such file or directory
do_configure_append() {
    if [ -d "${S}" ]; then
        install -m 555 ${S}/include/linux/netfilter_bridge/ebt_ulog.h ${STAGING_KERNEL_BUILDDIR}/usr/include/linux/netfilter_bridge/ebt_ulog.h
    fi
}

Change-Id: I7a60b53fedb13cf3feb5ff51c59178b272b682d2